# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('img', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('type', models.CharField(choices=[('herbal', 'عشبية صحية'), ('tools', 'أدوات الصحة'), ('snacks', 'سناكات صحية')], max_length=50, verbose_name='النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف دولي صالح', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='رقم الهاتف')),
                ('specialization', models.CharField(max_length=255, verbose_name='التخصص')),
                ('overview', models.TextField(blank=True, verbose_name='نبذة')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='nutritionists/', verbose_name='صورة الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionists', to='clinic.clinic', verbose_name='العيادة')),
            ],
            options={
                'verbose_name': 'أخصائي تغذية',
                'verbose_name_plural': 'أخصائيو التغذية',
                'db_table': 'nutritionist',
                'ordering': ['-created_at'],
            },
        ),
    ]
