# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية'),
        ),
        migrations.AddIndex(
            model_name='nutritionist',
            index=models.Index(fields=['user'], name='nutritionis_user_id_2013ee_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionist',
            index=models.Index(fields=['clinic'], name='nutritionis_clinic__3f9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nutritionist'], name='product_nutriti_881145_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='product_is_avai_451bf8_idx'),
        ),
    ]
