# Generated by Django 5.2.13 on 2026-06-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('nutritionists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20, verbose_name='اليوم')),
                ('is_open', models.BooleanField(default=False, verbose_name='مفتوح')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت الإغلاق')),
                ('online_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الخدمة الأونلاين')),
                ('online_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية الخدمة الأونلاين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='clinic.clinic', verbose_name='العيادة')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
            ],
            options={
                'verbose_name': 'التوفرية',
                'verbose_name_plural': 'التوفريات',
                'db_table': 'availability',
                'indexes': [models.Index(fields=['clinic', 'nutritionist'], name='availabilit_clinic__672761_idx'), models.Index(fields=['day'], name='availabilit_day_be7c53_idx')],
                'unique_together': {('clinic', 'nutritionist', 'day')},
            },
        ),
    ]
