# Generated by Django 6.0.3 on 2026-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0003_alter_nutritionist_id_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
