# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('nutritionists', '0001_initial'),
        ('patients', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مرجع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('type', models.CharField(choices=[('appointment', 'موعد'), ('product', 'منتج'), ('package', 'باقة'), ('workshop', 'ورشة عمل')], max_length=50, verbose_name='النوع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='معرف المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment', verbose_name='الموعد')),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.package', verbose_name='الباقة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'db_table': 'payment',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['patient', 'status'], name='payment_patient_ac8b46_idx'), models.Index(fields=['transaction_id'], name='payment_transac_9ff03c_idx')],
            },
        ),
    ]
