# Generated by Django 5.2.7 on 2026-06-16 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cart_cartitem_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='رقم المعاملة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='payments.order', verbose_name='الطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'معاملة دفع',
                'verbose_name_plural': 'معاملات الدفع',
                'db_table': 'payment_transaction',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
