# Generated by Django 5.2.13 on 2026-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='الرد'),
        ),
    ]
