# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم العيادة')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف دولي صالح', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='رقم الهاتف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='الشعار')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عيادة',
                'verbose_name_plural': 'العيادات',
                'db_table': 'clinic',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='clinic_email_9ffeb3_idx')],
            },
        ),
    ]
