# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPublication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('overview', models.TextField(verbose_name='النبذة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('last_sentence', models.CharField(blank=True, max_length=255, verbose_name='الجملة الأخيرة')),
                ('img', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('archived', 'مؤرشفة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
            ],
            options={
                'verbose_name': 'منشور تعليمي',
                'verbose_name_plural': 'المنشورات التعليمية',
                'db_table': 'educational_publication',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nutritionist', 'status'], name='educational_nutriti_0c43ab_idx'), models.Index(fields=['published_at'], name='educational_publish_373c26_idx')],
            },
        ),
    ]
