# Generated by Django 6.0.3 on 2026-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'اكتمل'), ('cancelled', 'ملغى'), ('no-show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('type', models.CharField(choices=[('online', 'أونلاين'), ('in-person', 'حضوري')], max_length=20, verbose_name='نوع الموعد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'db_table': 'appointment',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('content', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
