# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية'),
        ),
    ]
