# Generated by Django 5.2.7 on 2026-06-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة'), ('saturday', 'السبت'), ('sunday', 'الأحد')], max_length=20, unique=True, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت بداية الدوام')),
                ('end_time', models.TimeField(verbose_name='وقت انتهاء الدوام')),
            ],
            options={
                'verbose_name': 'جدول',
                'verbose_name_plural': 'الجداول',
                'db_table': 'schedule',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='الملاحظات'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'start_time')},
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
