# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الباقة')),
                ('details', models.TextField(verbose_name='مميزات الباقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الباقة')),
                ('num', models.IntegerField(verbose_name='مدة الباقة (بالشهور)')),
                ('first_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الدفعة الأولى')),
                ('category', models.CharField(choices=[('medical', 'إجراءات علاجية'), ('diet', 'حميات صحية')], max_length=20, verbose_name='نوع الباقة')),
                ('require_consultation', models.BooleanField(default=False, verbose_name='استشارة مسبقة')),
                ('status', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'db_table': 'package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='المكان')),
                ('type', models.CharField(choices=[('online', 'أونلاين'), ('in-person', 'حضوري')], max_length=20, verbose_name='النوع')),
                ('overview', models.TextField(verbose_name='النبذة')),
                ('img', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, null=True, verbose_name='الرابط')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('ongoing', 'جارية'), ('completed', 'اكتملت'), ('cancelled', 'ملغاة')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('num_participants', models.IntegerField(default=0, verbose_name='عدد المشاركين')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشاركين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
            ],
            options={
                'verbose_name': 'ورشة عمل',
                'verbose_name_plural': 'ورش العمل',
                'db_table': 'workshop',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PatientWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='patients.patient')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='subscriptions.workshop')),
            ],
            options={
                'verbose_name': 'اشتراك ورشة',
                'verbose_name_plural': 'اشتراكات الورش',
                'db_table': 'patient_workshop',
                'ordering': ['patient'],
            },
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['nutritionist', 'date'], name='workshop_nutriti_355f17_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status'], name='workshop_status_2c3f52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientworkshop',
            unique_together={('patient', 'workshop')},
        ),
    ]
