# Generated by Django 5.2.13 on 2026-06-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0003_alter_nutritionist_id_availability'),
        ('patients', '0003_alter_measurement_id_alter_patient_id_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientworkshop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='plans/', verbose_name='الملف')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='nutritionists.nutritionist', verbose_name='أخصائي التغذية')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'خطة غذائية',
                'verbose_name_plural': 'الخطط الغذائية',
                'db_table': 'plan',
                'ordering': ['-upload_at'],
                'indexes': [models.Index(fields=['patient', 'nutritionist'], name='plan_patient_1de624_idx')],
            },
        ),
    ]
