# Generated by Django 5.2.7 on 2026-06-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_patientworkshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للحضور'),
        ),
        migrations.CreateModel(
            name='WorkshopAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subscriptions.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'حضور ورشة',
                'verbose_name_plural': 'حضور الورش',
                'db_table': 'workshop_attendance',
                'ordering': ['-created_at'],
            },
        ),
    ]
