# Generated by Django 6.0.3 on 2026-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ القياس')),
                ('weight', models.FloatField(verbose_name='الوزن')),
                ('waist', models.FloatField(verbose_name='الخصر')),
                ('abdomen', models.FloatField(verbose_name='البطن')),
                ('hip', models.FloatField(verbose_name='الورك')),
                ('thigh', models.FloatField(verbose_name='الفخذ')),
                ('arm', models.FloatField(verbose_name='الذراع')),
                ('bmi', models.FloatField(verbose_name='مؤشر كتلة الجسم')),
            ],
            options={
                'verbose_name': 'قياس',
                'verbose_name_plural': 'القياسات',
                'db_table': 'measurement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='الطول')),
                ('start_weight', models.FloatField(verbose_name='الوزن عند البدء')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='صورة الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientInitialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_goal', models.CharField(blank=True, max_length=255)),
                ('followed_diet_before', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('child', 'طفل'), ('vegetarian', 'نباتي'), ('pregnant', 'حامل'), ('breastfeeding', 'مرضع')], max_length=50)),
                ('favorite_color', models.CharField(blank=True, max_length=100)),
                ('surgeries', models.TextField(blank=True)),
                ('last_analysis', models.TextField(blank=True)),
                ('doctor_diagnosis', models.TextField(blank=True)),
                ('visit_purpose', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('has_pressure', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_cholesterol', models.BooleanField(default=False)),
                ('has_colon', models.BooleanField(default=False)),
                ('has_constipation', models.BooleanField(default=False)),
                ('has_thyroid', models.BooleanField(default=False)),
                ('has_food_allergy', models.BooleanField(default=False)),
                ('has_pcos', models.BooleanField(default=False)),
                ('has_irregular_period', models.BooleanField(default=False)),
                ('takes_cortisone', models.BooleanField(default=False)),
                ('takes_birth_control', models.BooleanField(default=False)),
                ('takes_allergy_med', models.BooleanField(default=False)),
                ('takes_glucose_regulator', models.BooleanField(default=False)),
                ('takes_cycle_regulator', models.BooleanField(default=False)),
                ('takes_retan', models.BooleanField(default=False)),
            ],
        ),
    ]
