# Generated by Django 6.0.3 on 2026-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_measurement_id_alter_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_allergy_med',
        ),
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_birth_control',
        ),
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_cortisone',
        ),
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_cycle_regulator',
        ),
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_glucose_regulator',
        ),
        migrations.RemoveField(
            model_name='patientinitialinfo',
            name='takes_retan',
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='start_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن عند البدء'),
        ),
    ]
