# Generated by Django 6.0.3 on 2026-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255, verbose_name='مرسل الرسالة')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='الرد')),
                ('reply_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('sender_type', models.CharField(choices=[('patient', 'مريض'), ('visitor', 'زائر')], default='visitor', max_length=20, verbose_name='نوع المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('info', models.TextField(verbose_name='المعلومات')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('status', models.CharField(choices=[('unread', 'غير مقروءة'), ('read', 'مقروءة'), ('archived', 'مؤرشفة')], default='unread', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'db_table': 'notification',
                'ordering': ['-time'],
            },
        ),
    ]
