# Generated by Django 6.0.3 on 2026-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient', verbose_name='المريض (إن وجد)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient', verbose_name='المريض'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['email'], name='message_email_9e980f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='message_is_read_8eefe1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['patient', 'status'], name='notificatio_patient_d3ea27_idx'),
        ),
    ]
